# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Lab417\xio-intrusion-detection\gui\main_window_enhanced.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("background-color: rgb(12, 12, 12);\n"
"color: rgb(85, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 15)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titlelabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titlelabel.sizePolicy().hasHeightForWidth())
        self.titlelabel.setSizePolicy(sizePolicy)
        self.titlelabel.setMinimumSize(QtCore.QSize(0, 40))
        self.titlelabel.setMaximumSize(QtCore.QSize(16777215, 60))
        self.titlelabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titlelabel.setAutoFillBackground(False)
        self.titlelabel.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"font: 29pt \"宋体\";\n"
"color: rgb(90, 174, 242);\n"
"color: rgb(0, 255, 255);\n"
"color: rgb(85, 255, 255);")
        self.titlelabel.setScaledContents(True)
        self.titlelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titlelabel.setIndent(0)
        self.titlelabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.titlelabel.setObjectName("titlelabel")
        self.verticalLayout.addWidget(self.titlelabel)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_1.setSpacing(15)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_1.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_1.setSpacing(10)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setMinimumSize(QtCore.QSize(65, 30))
        self.pushButton_1.setMaximumSize(QtCore.QSize(70, 33))
        self.pushButton_1.setStyleSheet("color: rgb(198, 198, 198);\n"
"font: 12pt \"宋体\";\n"
"background-color: rgb(66, 66, 66);\n"
"selection-background-color: rgb(45, 45, 45);\n"
"color: rgb(85, 255, 255);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout_1.addWidget(self.pushButton_1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(65, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(70, 33))
        self.pushButton_2.setStyleSheet("color: rgb(198, 198, 198);\n"
"font: 12pt \"宋体\";\n"
"background-color: rgb(66, 66, 66);\n"
"selection-background-color: rgb(45, 45, 45);\n"
"color: rgb(85, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_1.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(65, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(70, 33))
        self.pushButton_3.setStyleSheet("color: rgb(198, 198, 198);\n"
"font: 12pt \"宋体\";\n"
"background-color: rgb(66, 66, 66);\n"
"selection-background-color: rgb(45, 45, 45);\n"
"color: rgb(85, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_1.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(65, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(70, 33))
        self.pushButton_4.setStyleSheet("color: rgb(198, 198, 198);\n"
"font: 12pt \"宋体\";\n"
"background-color: rgb(66, 66, 66);\n"
"selection-background-color: rgb(45, 45, 45);\n"
"color: rgb(85, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_1.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(65, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(70, 33))
        self.pushButton_5.setStyleSheet("color: rgb(198, 198, 198);\n"
"font: 12pt \"宋体\";\n"
"background-color: rgb(66, 66, 66);\n"
"selection-background-color: rgb(45, 45, 45);\n"
"color: rgb(85, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_1.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem)
        self.verticalLayout_1.setStretch(0, 1)
        self.verticalLayout_1.setStretch(1, 1)
        self.verticalLayout_1.setStretch(2, 1)
        self.verticalLayout_1.setStretch(3, 1)
        self.verticalLayout_1.setStretch(4, 1)
        self.verticalLayout_1.setStretch(5, 10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_1)
        self.videoLabel_1 = QtWidgets.QLabel(self.frame_1)
        self.videoLabel_1.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.videoLabel_1.setText("")
        self.videoLabel_1.setObjectName("videoLabel_1")
        self.horizontalLayout_2.addWidget(self.videoLabel_1)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout_2.setStretch(1, 100)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.videoLabel_2 = QtWidgets.QLabel(self.frame_1)
        self.videoLabel_2.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.videoLabel_2.setText("")
        self.videoLabel_2.setObjectName("videoLabel_2")
        self.horizontalLayout_3.addWidget(self.videoLabel_2)
        self.videoLabel_3 = QtWidgets.QLabel(self.frame_1)
        self.videoLabel_3.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.videoLabel_3.setText("")
        self.videoLabel_3.setObjectName("videoLabel_3")
        self.horizontalLayout_3.addWidget(self.videoLabel_3)
        self.videoLabel_4 = QtWidgets.QLabel(self.frame_1)
        self.videoLabel_4.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.videoLabel_4.setText("")
        self.videoLabel_4.setObjectName("videoLabel_4")
        self.horizontalLayout_3.addWidget(self.videoLabel_4)
        self.videoLabel_5 = QtWidgets.QLabel(self.frame_1)
        self.videoLabel_5.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.videoLabel_5.setText("")
        self.videoLabel_5.setObjectName("videoLabel_5")
        self.horizontalLayout_3.addWidget(self.videoLabel_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 25)
        self.verticalLayout_2.setStretch(1, 9)
        self.horizontalLayout_1.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logTitle = QtWidgets.QLabel(self.frame_2)
        self.logTitle.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"font: 22pt \"宋体\";\n"
"color: rgb(200, 200, 200);\n"
"color: rgb(90, 174, 242);\n"
"color: rgb(85, 255, 255);")
        self.logTitle.setIndent(10)
        self.logTitle.setObjectName("logTitle")
        self.verticalLayout_3.addWidget(self.logTitle)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setStyleSheet("gridline-color: rgb(25, 25, 25);\n"
"font: 16pt \"宋体\";\n"
"background-color: rgb(25, 25, 25);\n"
"border-color: rgb(25, 25, 25);\n"
"color: rgb(200, 200, 200);")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.recordTitle = QtWidgets.QLabel(self.frame_2)
        self.recordTitle.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"font: 22pt \"宋体\";\n"
"color: rgb(200, 200, 200);\n"
"color: rgb(90, 174, 242);\n"
"color: rgb(85, 255, 255);")
        self.recordTitle.setIndent(10)
        self.recordTitle.setObjectName("recordTitle")
        self.verticalLayout_3.addWidget(self.recordTitle)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.recordLabel = QtWidgets.QLabel(self.frame_3)
        self.recordLabel.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.recordLabel.setText("")
        self.recordLabel.setObjectName("recordLabel")
        self.horizontalLayout_6.addWidget(self.recordLabel)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_3.setStretch(0, 9)
        self.verticalLayout_3.setStretch(1, 51)
        self.verticalLayout_3.setStretch(2, 9)
        self.verticalLayout_3.setStretch(3, 51)
        self.horizontalLayout_1.addWidget(self.frame_2)
        self.horizontalLayout_1.setStretch(0, 7)
        self.horizontalLayout_1.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"selection-background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.processMenu = QtWidgets.QMenu(self.menubar)
        self.processMenu.setObjectName("processMenu")
        self.viewMenu = QtWidgets.QMenu(self.menubar)
        self.viewMenu.setObjectName("viewMenu")
        self.setupMenu = QtWidgets.QMenu(self.menubar)
        self.setupMenu.setObjectName("setupMenu")
        self.streamMenu = QtWidgets.QMenu(self.menubar)
        self.streamMenu.setObjectName("streamMenu")
        self.statisticsMenu = QtWidgets.QMenu(self.menubar)
        self.statisticsMenu.setObjectName("statisticsMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.fullScreen = QtWidgets.QAction(MainWindow)
        self.fullScreen.setObjectName("fullScreen")
        self.start = QtWidgets.QAction(MainWindow)
        self.start.setObjectName("start")
        self.stop = QtWidgets.QAction(MainWindow)
        self.stop.setObjectName("stop")
        self.openConfigFile = QtWidgets.QAction(MainWindow)
        self.openConfigFile.setObjectName("openConfigFile")
        self.stream_1 = QtWidgets.QAction(MainWindow)
        self.stream_1.setObjectName("stream_1")
        self.stream_2 = QtWidgets.QAction(MainWindow)
        self.stream_2.setObjectName("stream_2")
        self.stream_3 = QtWidgets.QAction(MainWindow)
        self.stream_3.setObjectName("stream_3")
        self.stream_4 = QtWidgets.QAction(MainWindow)
        self.stream_4.setObjectName("stream_4")
        self.stream_5 = QtWidgets.QAction(MainWindow)
        self.stream_5.setObjectName("stream_5")
        self.exitFullScreen = QtWidgets.QAction(MainWindow)
        self.exitFullScreen.setObjectName("exitFullScreen")
        self.openStatistics = QtWidgets.QAction(MainWindow)
        self.openStatistics.setObjectName("openStatistics")
        self.processMenu.addAction(self.start)
        self.processMenu.addAction(self.stop)
        self.viewMenu.addAction(self.fullScreen)
        self.viewMenu.addAction(self.exitFullScreen)
        self.setupMenu.addAction(self.openConfigFile)
        self.streamMenu.addAction(self.stream_1)
        self.streamMenu.addAction(self.stream_2)
        self.streamMenu.addAction(self.stream_3)
        self.streamMenu.addAction(self.stream_4)
        self.streamMenu.addAction(self.stream_5)
        self.statisticsMenu.addAction(self.openStatistics)
        self.menubar.addAction(self.processMenu.menuAction())
        self.menubar.addAction(self.streamMenu.menuAction())
        self.menubar.addAction(self.viewMenu.menuAction())
        self.menubar.addAction(self.statisticsMenu.menuAction())
        self.menubar.addAction(self.setupMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titlelabel.setText(_translate("MainWindow", "西奥电梯智能安全监测系统"))
        self.pushButton_1.setText(_translate("MainWindow", "SWNN-1"))
        self.pushButton_2.setText(_translate("MainWindow", "SWNN-2"))
        self.pushButton_3.setText(_translate("MainWindow", "专机下线"))
        self.pushButton_4.setText(_translate("MainWindow", "喷粉上线"))
        self.pushButton_5.setText(_translate("MainWindow", "薄板通用"))
        self.logTitle.setText(_translate("MainWindow", "实时检测信息"))
        self.recordTitle.setText(_translate("MainWindow", "异常记录"))
        self.processMenu.setTitle(_translate("MainWindow", "程序"))
        self.viewMenu.setTitle(_translate("MainWindow", "显示"))
        self.setupMenu.setTitle(_translate("MainWindow", "设置"))
        self.streamMenu.setTitle(_translate("MainWindow", "视频流"))
        self.statisticsMenu.setTitle(_translate("MainWindow", "统计"))
        self.fullScreen.setText(_translate("MainWindow", "全屏模式"))
        self.start.setText(_translate("MainWindow", "运行"))
        self.stop.setText(_translate("MainWindow", "终止"))
        self.openConfigFile.setText(_translate("MainWindow", "打开配置文件"))
        self.stream_1.setText(_translate("MainWindow", "萨瓦尼尼-1"))
        self.stream_2.setText(_translate("MainWindow", "萨瓦尼尼-2"))
        self.stream_3.setText(_translate("MainWindow", "专机下线"))
        self.stream_4.setText(_translate("MainWindow", "喷粉上线"))
        self.stream_5.setText(_translate("MainWindow", "薄板通用"))
        self.exitFullScreen.setText(_translate("MainWindow", "退出全屏"))
        self.openStatistics.setText(_translate("MainWindow", "异常情况统计与可视化"))
